Rehabilitation/Controllers/AuthorizeController.cs
using Rehabilitation.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rehabilitation.Controllers
{
    public class AuthorizeController : Controller
    {
        private RehabilitationEntities db = new RehabilitationEntities();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        //[HttpGet]
        //public ActionResult Sign_In()
        //{
        //    var LoginModel = new Account();

        //    return View(LoginModel);
        //}
        public new RedirectToRouteResult RedirectToAction(string action, string controller)
        {
            return base.RedirectToAction(action, controller);
        }

        [HttpPost]
        public ActionResult Sign_In(Account model)
        {
            Account account = db.Accounts.Find(model.Username);
            if (account == null)
                ViewBag.Text = "Không tìm thấy tài khoản.";
            else if (EncMD5(model.Password) == account.Password)
            {
                ViewBag.Text = "Đăng nhập thành công.";
                Session["username"] = account.Username;
                Session["role"] = account.Role;
                return RedirectToAction("Index", "Home");
            }
            else
                ViewBag.Text = "Mật khẩu không chính xác.";
            return View("Index");
        }

        public ActionResult Sign_Out()
        {
            //Session.Remove("Username");
            //Session.Remove("Role");
            Session["Username"] = null;
            Session["Role"] = null;
            return RedirectToAction("Index");
        }

        public ActionResult ChangePassword()
        {
            Account account = db.Accounts.Find(Session["Username"].ToString());
            return View(account);
        }

        [HttpPost]
        public ActionResult ChangePassword(Account account)
        {
            Account old = db.Accounts.Find(Session["Username"].ToString());
            db.Entry(old).State = EntityState.Detached;
            if (EncMD5(account.Password) == old.Password)
            {
                account.LastModified = DateTime.Now;
                account.Password = EncMD5(account.NewPassword);
                db.Entry(account).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(account);
        }

        private string EncMD5(string password)
        {
            password = (password == null) ? "" : password;
            System.Security.Cryptography.MD5 md5 = new System.Security.Cryptography.MD5CryptoServiceProvider();
            System.Text.UTF8Encoding encoder = new System.Text.UTF8Encoding();
            Byte[] originalBytes = encoder.GetBytes(password);
            Byte[] encodedBytes = md5.ComputeHash(originalBytes);
            password = BitConverter.ToString(encodedBytes).Replace("-", "");
            var result = password.ToLower();
            return result;
        }
    }
}

Rehabilitation/Views/Authorize/ChangePassword.cshtml
@model Rehabilitation.Models.Account

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/css/login.css" rel="stylesheet" />
</head>
<body>
    @using (Html.BeginForm())
    {
        <div class="login-page">
            <div class="form">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Username)

                @Html.PasswordFor(model => model.Password, new { placeholder = "Mật khẩu hiện tại" })
                @Html.ValidationMessageFor(model => model.Password)

                @Html.PasswordFor(model => model.NewPassword, new { placeholder = "Mật khẩu mới" })
                @Html.ValidationMessageFor(model => model.NewPassword)

                @Html.PasswordFor(model => model.ConfirmPassowrd, new { placeholder = "Xác nhận mật khẩu mới" })
                @Html.ValidationMessageFor(model => model.ConfirmPassowrd)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Role)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Created)
                <input type="submit" value="lưu" />
                <label>@ViewBag.Text</label>
            </div>
        </div>
    }
</body>
</html>

Rehabilitation/Views/Authorize/Index.cshtml
@model Rehabilitation.Models.Account

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/css/login.css" rel="stylesheet" />
</head>
<body>
    @using (Html.BeginForm("Sign_In", "Authorize"))
    {
    <div class="login-page">
        <div class="form">
            @Html.TextBoxFor(model => model.Username, new { placeholder = "Tên đăng nhập" })
            @Html.PasswordFor(model => model.Password, new { placeholder = "Mật khẩu" })
            <input type="submit" value="đăng nhập" />
            <label>@ViewBag.Text</label>
        </div>
    </div>
    }
</body>
</html>