Rehabilitation/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rehabilitation.Filters;
using Rehabilitation.Models;

namespace Rehabilitation.Controllers
{
    [LoginFilter]
    public class PatientsController : Controller
    {
        private RehabilitationEntities db = new RehabilitationEntities();

        // GET: Patients
        [RoleFilter(Role = "Doctor")]
        public ActionResult Index(string search)
        {
            var patients = from m in db.Patients
                           select m;

            if (!String.IsNullOrEmpty(search))
            {
                patients = patients.Where(s => s.Name.Contains(search));
            }

            return View(patients.ToList());
        }

        // GET: Patients/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else if (Session["Role"].ToString() == "Patient" && id != Session["Username"].ToString())
                return new HttpStatusCodeResult(401);
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: Patients/Create
        [RoleFilter(Role = "Doctor")]
        public ActionResult Create()
        {
            ViewBag.DoctorId = new SelectList(db.Doctors, "DoctorId", "DoctorName");
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleFilter(Role = "Doctor")]
        public ActionResult Create([Bind(Include = "PatientId,Name,Birth,Sex,Job,Ethnicity,Adress,Workplace,FeeType,InsuranceId,InsuranceExpired,HospitalizedDate,Status,ReleasedOrDeath,Photo,DoctorId,Eating,Grooming,Bathing,DressingUpperBody,DressingLowerBody,Toileting,BladderManagement,BowelManagement,TransferBedChairWheelchair,TransferToilet,TransferTubShower,WalkOrWheelchair,Stairs,Compreshension,Expression,SocialInteraction,ProblemSolving,Memory")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                patient.Created = DateTime.Now;
                patient.LastModified = DateTime.Now;
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DoctorId = new SelectList(db.Doctors, "DoctorId", "DoctorName", patient.DoctorId);
            return View(patient);
        }

        // GET: Patients/Edit/5
        [RoleFilter(Role = "Doctor")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            ViewBag.DoctorId = new SelectList(db.Doctors, "DoctorId", "DoctorName", patient.DoctorId);
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleFilter(Role = "Doctor")]
        public ActionResult Edit([Bind(Include = "PatientId,Name,Birth,Sex,Job,Ethnicity,Adress,Workplace,FeeType,InsuranceId,InsuranceExpired,HospitalizedDate,Status,ReleasedOrDeath,Photo,DoctorId,Eating,Grooming,Bathing,DressingUpperBody,DressingLowerBody,Toileting,BladderManagement,BowelManagement,TransferBedChairWheelchair,TransferToilet,TransferTubShower,WalkOrWheelchair,Stairs,Compreshension,Expression,SocialInteraction,ProblemSolving,Memory,Created")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                patient.LastModified = DateTime.Now;
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DoctorId = new SelectList(db.Doctors, "DoctorId", "DoctorName", patient.DoctorId);
            return View(patient);
        }

        [RoleFilter(Role = "Doctor")]
        public ActionResult EditFIM(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FIMModel model = new FIMModel();
            model.Patient = db.Patients.Find(id);
            if (model.Patient == null)
            {
                return HttpNotFound();
            }
            //ViewBag.DoctorId = new SelectList(db.Doctors, "DoctorId", "DoctorName", patient.DoctorId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleFilter(Role = "Doctor")]
        public ActionResult EditFIM(FIMModel model)
        {
            if (ModelState.IsValid)
            {
                Patient old = db.Patients.Find(model.Patient.PatientId);
                db.Entry(old).State = EntityState.Detached;

                model.Trace.PatientId = old.PatientId;
                model.Trace.Bathing_B = old.Bathing;
                model.Trace.Eating_B = old.Eating;
                model.Trace.Grooming_B = old.Grooming;
                model.Trace.DressingLowerBody_B = old.DressingLowerBody;
                model.Trace.DressingUpperBody_B = old.DressingUpperBody;
                model.Trace.Toileting_B = old.Toileting;
                model.Trace.BladderManagement_B = old.BladderManagement;
                model.Trace.BowelManagement_B = old.BowelManagement;
                model.Trace.TransferBedChairWheelchair_B = old.TransferBedChairWheelchair;
                model.Trace.TransferToilet_B = old.TransferToilet;
                model.Trace.TransferTubShower_B = old.TransferTubShower;
                model.Trace.WalkOrWheelchair_B = old.WalkOrWheelchair;
                model.Trace.Stairs_B = old.Stairs;
                model.Trace.Compreshension_B = old.Compreshension;
                model.Trace.Expression_B = old.Expression;
                model.Trace.SocialInteraction_B = old.SocialInteraction;
                model.Trace.ProblemSolving_B = old.ProblemSolving;
                model.Trace.Memory_B = old.Memory;

                model.Trace.Bathing_A = model.Patient.Bathing.Value;
                model.Trace.Eating_A = model.Patient.Eating.Value;
                model.Trace.Grooming_A = model.Patient.Grooming.Value;
                model.Trace.DressingLowerBody_A = model.Patient.DressingLowerBody.Value;
                model.Trace.DressingUpperBody_A = model.Patient.DressingUpperBody.Value;
                model.Trace.Toileting_A = model.Patient.Toileting.Value;
                model.Trace.BladderManagement_A = model.Patient.BladderManagement.Value;
                model.Trace.BowelManagement_A = model.Patient.BowelManagement.Value;
                model.Trace.TransferBedChairWheelchair_A = model.Patient.TransferBedChairWheelchair.Value;
                model.Trace.TransferToilet_A = model.Patient.TransferToilet.Value;
                model.Trace.TransferTubShower_A = model.Patient.TransferTubShower.Value;
                model.Trace.WalkOrWeelchair_A = model.Patient.WalkOrWheelchair.Value;
                model.Trace.Stairs_A = model.Patient.Stairs.Value;
                model.Trace.Compreshension_A = model.Patient.Compreshension.Value;
                model.Trace.Expression_A = model.Patient.Expression.Value;
                model.Trace.SocialInteraction_A = model.Patient.SocialInteraction.Value;
                model.Trace.ProblemSolving_A = model.Patient.ProblemSolving.Value;
                model.Trace.Memory_A = model.Patient.Memory.Value;

                model.Patient.LastModified = DateTime.Now;

                db.Entry(model.Patient).State = EntityState.Modified;
                //db.Entry(model.Trace).State = EntityState.Modified;
                db.Traces.Add(model.Trace);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.DoctorId = new SelectList(db.Doctors, "DoctorId", "DoctorName", model.Patient.DoctorId);
            return View(model);
            //if (ModelState.IsValid)
            //{
            //    db.Entry(patient).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //ViewBag.DoctorId = new SelectList(db.Doctors, "DoctorId", "DoctorName", patient.DoctorId);
            //return View(patient);
        }

        // GET: Patients/Delete/5
        [RoleFilter(Role = "Admin")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RoleFilter(Role = "Admin")]
        public ActionResult DeleteConfirmed(string id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            try
            {
                db.SaveChanges();
            }

Rehabilitation/Controllers/TracesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rehabilitation.Filters;
using Rehabilitation.Models;

namespace Rehabilitation.Controllers
{
    [LoginFilter]
    public class TracesController : Controller
    {
        private RehabilitationEntities db = new RehabilitationEntities();

        // GET: Traces
        [RoleFilter(Role = "Admin")]
        public ActionResult Index()
        {
            var traces = db.Traces.Include(t => t.Patient);
            return View(traces.ToList());
        }

        public ActionResult TrainingHistory(string id)
        {
            var traces = db.Traces.Where(p => p.PatientId == id).Include(p => p.Patient).OrderByDescending(p => p.Time);
            return View(traces.ToList());
        }

        // GET: Traces/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trace trace = db.Traces.Find(id);
            if (trace == null)
            {
                return HttpNotFound();
            }
            return View(trace);
        }

        // GET: Traces/Create
        [RoleFilter(Role = "Admin")]
        public ActionResult Create()
        {
            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name");
            return View();
        }

        // POST: Traces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleFilter(Role = "Admin")]
        public ActionResult Create([Bind(Include = "TraceId,PatientId,Exercise,Time,Eating_B,Eating_A,Grooming_B,Grooming_A,Bathing_B,Bathing_A,DressingUpperBody_B,DressingUpperBody_A,DressingLowerBody_B,DressingLowerBody_A,Toileting_B,Toileting_A,BladderManagement_B,BladderManagement_A,BowelManagement_B,BowelManagement_A,TransferBedChairWheelchair_B,TransferBedChairWheelchair_A,TransferToilet_B,TransferToilet_A,TransferTubShower_B,TransferTubShower_A,WalkOrWheelchair_B,WalkOrWeelchair_A,Stairs_B,Stairs_A,Compreshension_B,Compreshension_A,Expression_B,Expression_A,SocialInteraction_B,SocialInteraction_A,ProblemSolving_B,ProblemSolving_A,Memory_B,Memory_A")] Trace trace)
        {
            if (ModelState.IsValid)
            {
                db.Traces.Add(trace);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", trace.PatientId);
            return View(trace);
        }

        // GET: Traces/Edit/5
        [RoleFilter(Role = "Admin")]
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trace trace = db.Traces.Find(id);
            if (trace == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", trace.PatientId);
            return View(trace);
        }

        // POST: Traces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleFilter(Role = "Admin")]
        public ActionResult Edit([Bind(Include = "TraceId,PatientId,Exercise,Time,Eating_B,Eating_A,Grooming_B,Grooming_A,Bathing_B,Bathing_A,DressingUpperBody_B,DressingUpperBody_A,DressingLowerBody_B,DressingLowerBody_A,Toileting_B,Toileting_A,BladderManagement_B,BladderManagement_A,BowelManagement_B,BowelManagement_A,TransferBedChairWheelchair_B,TransferBedChairWheelchair_A,TransferToilet_B,TransferToilet_A,TransferTubShower_B,TransferTubShower_A,WalkOrWheelchair_B,WalkOrWeelchair_A,Stairs_B,Stairs_A,Compreshension_B,Compreshension_A,Expression_B,Expression_A,SocialInteraction_B,SocialInteraction_A,ProblemSolving_B,ProblemSolving_A,Memory_B,Memory_A")] Trace trace)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trace).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", trace.PatientId);
            return View(trace);
        }

        // GET: Traces/Delete/5
        [RoleFilter(Role = "Admin")]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trace trace = db.Traces.Find(id);
            if (trace == null)
            {
                return HttpNotFound();
            }
            return View(trace);
        }

        // POST: Traces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RoleFilter(Role = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Trace trace = db.Traces.Find(id);
            db.Traces.Remove(trace);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rehabilitation/Views/Patients/Delete.cshtml
@model Rehabilitation.Models.Patient

@{
    ViewBag.Title = "Xóa";
}

    <h2>Xóa</h2>

<h3>Bạn có chắc chắn muốn xóa bệnh án này không?</h3>
<div>
    <h4>Bệnh án</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SexToString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ethnicity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ethnicity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Workplace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Workplace)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HospitalizedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalizedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleasedOrDeath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleasedOrDeath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở lại danh sách", "Index")
        </div>
    }
</div>

Rehabilitation/Views/Patients/Details.cshtml
@model Rehabilitation.Models.Patient

@{
    ViewBag.Title = "Chi tiết";
}
<h2>Chi tiết</h2>

<div>
    <h4>Bệnh án</h4>
    <hr />
    <p>
        @Html.ActionLink("Chỉnh sửa thông tin", "Edit", new { id = Model.PatientId }) |
        @Html.ActionLink("Thêm kết quả luyện tập", "EditFIM", new { id = Model.PatientId }) |
        @Html.ActionLink("Xem lịch sử luyện tập", "TrainingHistory", "Traces", new { id = Model.PatientId }, null) |
        @Html.ActionLink("Trở lại danh sách", "Index")
    </p>
    <dl class="dl-horizontal">
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">Thông tin bệnh nhân</legend>
            <dt>
                @Html.DisplayNameFor(model => model.PatientId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PatientId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Birth)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Birth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sex)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SexToString)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Job)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Job)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ethnicity)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ethnicity)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Workplace)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Workplace)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HospitalizedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HospitalizedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ReleasedOrDeath)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReleasedOrDeath)
            </dd>

            <dt>
                Bác sĩ điều trị
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Doctor.DoctorName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Created)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Created)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastModified)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastModified)
            </dd>

        </fieldset>
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">Mức độ thực hiện chức năng độc lập [@Html.DisplayFor(model => model.Total)/126]</legend>
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Tiểu mục Vận động, di chuyển [@Html.DisplayFor(model => model.MotorDomain)/91]</legend>
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Tự chăm sóc</legend>
                    <dt>
                        @Html.DisplayNameFor(model => model.Eating)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Eating)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Grooming)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Grooming)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Bathing)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Bathing)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DressingUpperBody)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DressingUpperBody)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DressingLowerBody)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DressingLowerBody)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Toileting)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Toileting)
                    </dd>

                </fieldset>

                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Kiểm soát cơ tròn</legend>
                    <dt>
                        @Html.DisplayNameFor(model => model.BladderManagement)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BladderManagement)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.BowelManagement)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BowelManagement)
                    </dd>
                </fieldset>

                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Dịch chuyển</legend>
                    <dt>
                        @Html.DisplayNameFor(model => model.TransferBedChairWheelchair)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TransferBedChairWheelchair)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TransferToilet)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TransferToilet)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TransferTubShower)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TransferTubShower)
                    </dd>
                </fieldset>

                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Di chuyển, đi lại</legend>
                    <dt>
                        @Html.DisplayNameFor(model => model.WalkOrWheelchair)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.WalkOrWheelchair)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Stairs)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Stairs)
                    </dd>
                </fieldset>
            </fieldset>

            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Tiểu mục Nhận thức [@Html.DisplayFor(model => model.CognitiveDomain)/35]</legend>
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Giao tiếp</legend>
                    <dt>
                        @Html.DisplayNameFor(model => model.Compreshension)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Compreshension)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Expression)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Expression)
                    </dd>
                </fieldset>

                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Nhận thức xã hội</legend>
                    <dt>
                        @Html.DisplayNameFor(model => model.SocialInteraction)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SocialInteraction)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ProblemSolving)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ProblemSolving)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Memory)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Memory)
                    </dd>
                </fieldset>
            </fieldset>
        </fieldset>
</dl>
</div>

Rehabilitation/Views/Patients/Index.cshtml
@model IEnumerable<Rehabilitation.Models.Patient>

@{
    ViewBag.Title = "Danh sách bệnh án";
}

    <h2>Danh sách bệnh án</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")

    @using (Html.BeginForm()){    
         <p>@Html.TextBox("Search")
         <input type="submit" value="Lọc" /></p> 
        } 
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Job)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ethnicity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Workplace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HospitalizedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleasedOrDeath)
        </th>
        <th>
            Bác sĩ điều trị
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SexToString)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Job)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ethnicity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Workplace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HospitalizedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleasedOrDeath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doctor.DoctorName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Chi tiết", "Details", new { id = item.PatientId }) |
            @Html.ActionLink("Sửa", "Edit", new { id = item.PatientId }) |
            @Html.ActionLink("Xóa", "Delete", new { id = item.PatientId })
        </td>
    </tr>
}

</table>